FROM node:14 as frontend
COPY . /app
WORKDIR /app
RUN npm install -g gulp-cli && yarn install && gulp build

FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code 
WORKDIR /code
COPY . /code/
COPY --from=frontend /app/opensplit/static /code/opensplit/static
RUN python -m pip install -r requirements.txt
CMD "./start.sh"
