# Generated by Django 3.1.12 on 2021-06-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expense_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='payed_by',
            new_name='paid_by',
        ),
    ]
