# Generated by Django 3.1.12 on 2021-06-02 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20210602_2051"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="organization",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.organization"
            ),
            preserve_default=False,
        ),
    ]
