# Generated by Django 3.1.12 on 2021-06-02 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_expense_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization'),
        ),
    ]
