# Generated by Django 3.1.12 on 2021-06-02 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210602_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.organization'),
        ),
    ]
