# Generated by Django 3.1.12 on 2021-06-02 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210602_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='value',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='value',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='share',
            old_name='value',
            new_name='amount',
        ),
    ]
