# Generated by Django 3.1.12 on 2021-06-06 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210602_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='organization',
            name='token',
            field=models.CharField(default='asdf', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='share',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.expense'),
        ),
    ]
