name: Build and deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: yarn install
      - run: npm install -g gulp-cli
      - run: gulp build

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: opensplit/opensplit
          file: Dockerfile-prod
          context: .

      - name: Trigger Portainer to update the container
        run: curl -X POST ${{ secrets.PORTAINER_WEBHOOK }}
